# Generated by Django 4.0.3 on 2022-04-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='', max_length=300),
        ),
    ]
